#!/bin/bash
# Usage: sizeof <dir | file>
# Get a quick, easy to read size of the directory/file,
# while ignoring all the permission denied errors.
# Limitations: does not count files outside of permission scope
du -sh $1 2>/dev/null
